--- 
- name: Deploy and star Apache HTTPD service
  hosts: webserver
  vars:
    web_pkg: httpd
    firewalld_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: python-httplib2
    rule: http
  tasks:
   - name : Required packages are installed and up to date
     yum:
       name:
         - "{{ web_pkg }}"
         - "{{ firewalld_pkg }}"
         - "{{ python_pkg }}"
       state: latest


   - name: The {{ firewall_service }} service is started and enabled
     service: 
       name: "{{ firewall_service }}"
       enabled: true
       state: started

   - name: The {{ webs_service }} service is started and enabled
     service:
       name: "{{ web_service }}"
       enabled: true
       state: started

   - name: Web content is in place
     copy:
       content: "Example web content"
       dest: /var/www/html/index.html


   - name: The firewall port for {{ rule}} is open
     firewalld:
       service: "{{rule}}"
       permanent: true
       immediate: true
       state: enabled

- name: Verify the Apache service       
  hosts: localhost
  become: false
  tasks: 
    - name: Ensure that webserver is reachable 
      uri:
        url: http://servera.lab.example.com
        status:_code: 200




