---
# tasks file for student.myenv
#
- name: check myenv_user default
  fail:
    msg: You must specify the variable 'myenv_user' to use this role!
  when: "myenv_user == ''"


- name: install my packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ myenv_packages}}"

- name: copy place holder profile pic
  copy:
     src: profile.png
     dest: "~{{ myenv_user }}/profile.png"

- name: set and alias in '.bashrc'
  lineinfile:
    line: "alias tree='tree -C'"
    dest: "~{{ myenv_user }}/.bashrc"

- name: template otu mkcd function
  template: 
    src: mkcd.sh.j2
    dest: /etc/profile.d/mkcd.sh
    owner: root
    group: root
    mode: 0644


