---
# tasks file for myapache

- name: install apache packages
  yum:
    name: httpd
    state: latest

- name: install firewalld package
  yum:
    name: firewalld
    state: latest

- name: template out apache configuration
  template:
    src: apache_httpdconf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0444
  notify:
    - restart apache
  when: apache_enable


- name: template out 
