---
- name: Use vhost role playbook
  hosts: webservers

  pre_tasks:
     - debug:
         msg: ' Beginning web server configuration '

  roles:
    - myvhost

  post_tasks:
     - debug:
         msg: ' Websever has been configured '

