---
  - name: Install and start the databases and webservers
    yum:
      name: 
        - "{{ ansible_local.custom.packages.db_package }}"
        - "{{ ansible_local.custom.packages.web_package }}"
      state: latest

  - name: Start the database service
    service:
      name: "{{ ansible_local.custom.services.db_service }}"
      state: started
      enabled: true
  - name: Start the web service
    service:
      name: "{{ ansible_local.custom.services.web_services }}"
      state: started
      enabled: true


