---
- name: Install remote facts
  hosts: webserver
  vars: 
    remote_dir: /etc/ansible/facts.d
    fact_file: custom.fact
  tasks:
    - name: Create remote directory
      file: 
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: Install the new facts
      copy:
        src: "{{ fact_file }}"
        dest: "{{ remote_dir }}"

